[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 15
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
name = "contrato-educacional-backend"

[env]
FLASK_ENV = "production"
FLASK_APP = "app.py"
PYTHONUNBUFFERED = "1" 